---
- name: "Creates backend app directory"
  file:
    paths: ~/backend-app
    state: directory

- name: "Copy compiled backend app"
  copy:
      src: dist.zip
      dest: "~/backend-app/dist.zip"

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing node dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Executing node"
  shell: |
      export
      cd ~/backend-app
      pm2 start main.js --update-env
  register: execute_node

- name: print message
  debug:
      msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
