---
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend-app
    npm i
- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

- name: "install node_exporter"
  shell: |
    sudo useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.3.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.3.1.linux-amd64.tar.gz node_exporter-1.3.1.linux-amd64

- name: Creating node-exporter.service
  copy:
    dest: /etc/systemd/system/node-exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter Service
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target

- name: "Configure systemd"
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter